account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/',views.Login,name='Login'),
    path('logout/',views.Logout,name='Logout'),
    path('register/',views.Register,name='Register'),
    path('dashboard/',views.Dashboard,name='Dashboard'),
    path('dashboard/type-user/',views.CreateTypeUser,name='CreateTypeUser'),
    path('profile/',views.ProfileView,name='Profile'),
    path('profile/edit/<user_id>',views.EditProfile,name='EditProfile')
    
]

api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('api_courses.urls',namespace='api_courses')),
    path('chat/',include('chat.urls',namespace='chat')),
    path('account/',include('account.urls',namespace='account')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/cliente/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <title>Profile</title>
</head>
<body>
    {% block container %}
      
    {% endblock %}
    {% block domready %}
      
    {% endblock %}
</body>
</html>

templates/cliente/profile.html
{% extends "cliente/base.html" %}
{% block container %}
{% if request.user.is_authenticated %}
<div class="container-profile">
    <div class="body-profile">
        <div class="cont-img-profile">
            <img src="" class="img-profile" alt="{{request.user.first_name}}" >
        </div>
        <div>            
            <div class="logout-user">
                <form action="{% url 'account:Logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Cerrar Session">
                </form>
            </div>           
            <h2>Username: {{ request.user.username }}</h3>  
            <div>
                <a href="{% url 'account:EditProfile' request.user.id %}">Editar perfil</a>
            </div> 
            <div class="cont-notificacion-btn-count">
                <button class="btn-noti-count">
                    <span>Notificación</span>
                    <span class="circle"></span>
                </button>
            </div>                     
        </div>
    </div>
</div>
{% endif %}
{% endblock %}